import { useRouter } from 'next/router'
import Head from 'next/head'


const apiUrl = 'https://rickandmortyapi.com/api/character/'
  

// class Episodes extends Component {
//   render() {
//     const listItems = this.props.eps.map((d) => <li key={d}>{d}</li>);
//     return listItems;
//   }
// }


export async function getServerSideProps({query}) {

  const {id} = query;
  const res = await fetch(`${apiUrl}/${id}`);
  const data = await res.json();
  return {
    props: {
      data
    }, 
  }
}




  //  function renderComponent( {data}){
  //    const epi = [{episode}];
  
  //      const list = [];
  
  //      epi.forEach((ep) => {
   
    
  //     export async function getServerSideProps({ep}) {
      
      
  //         const res = await fetch(epi);
  //         const data = await res.json();
  //         return {
  //              props: {
  //                  data
  //               }, 
  //              }
  //            }
  //                list.push({ep})
  //              })
          
  //              console.log(list)
  //             return (
  //                 <div>
  //                  </div>
  //                )
            
  //              }




            
            
            export default function Character({data}) {
              const {id, name , image,status ,species,episode} = data;
              
              const eps = [];
              
              // console.log(data.episode)
              data.episode.forEach(ep => {
                fetch(ep)
                .then(response => response.json())
                .then(data => eps.push(data.id + ' ' + data.name + ' ' + data.air_date));
                
              });
              console.log( eps);

              

              return (
                <div >
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        
        <div >
          <div className="divbtn">
        <a href="../" ><button className="btn"><i className="arrow left"></i></button></a>
        </div>
            <ul >
             
             
            <li >
              
              
                <h1>{name}</h1>
                <img src={image} alt={`$name`} />
               
                <br />
                <p><span  className="dot"></span>   {status} - {species}</p>
                
                
                 </li>

                   <h3>Episodes:</h3>
                   <ul>
                   {eps.map(fet => {
                      const {eks} = eps;
                      return(
                        <li key={eks}>
                            {eks}
                        </li>
                      )
                   })}
                 
                   

                 
                  {/* <Episodes  eps={eps} /> */}



                 </ul>
                
            
            </ul>
           

        
        </div> 
     

    

    <style jsx global> {`
    body{
        background-color: rgba(36,40,47,255);
        color: #fff;
        
    }
    ul {
      list-style: none;
    }
    .dot {
      height: 10px;
      width: 10px;
      
      background-color: lime;
      border-radius: 50%;
      display:inline-block;
    }
    img {
      border-radius: 5px;
    }
    h3 {
      text-decoration: underline;
      text-decoration-color: orange;
    }
    .arrow {
      border: solid white;
      border-width: 0 3px 3px 0;
      display: inline-block;
      padding: 3px;
    }
    
    .left {
      transform: rotate(135deg);
      -webkit-transform: rotate(135deg);
    }
    .btn{
      height: 40px;
      width: 40px;
      border-radius: 50%;
      background-color: orange;      
    }
    .divbtn{
      position:absolute;
      top: 20px;
      left:20px;
    }
    

    `} </style>
    </div>
  )
}

