
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link';

export default function Home({data}) {
  const { results = [] } = data;
    

  console.log(data)
  return (
    <div className={styles.container}>
      <Head>
        <title>Rick & Morty</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Rick & Morty
        </h1>
          <br />
        <p className={styles.description}>
        <div>
          
          
          <select  className={styles.dropdown}>
            
            <option >Sort by status</option>
            <option >Alive</option>
            <option >Unknown</option>
            <option >Dead</option>
           
          </select>
          &nbsp;
          <select  className={styles.dropdown}>
            
            <option >Sort by gender</option>
            <option >Male</option>
            <option >Female</option>
          
           
          </select>
          </div>
        </p>

        <div  >
          
            <ul className={styles.grid}>
              <div className={styles.titlein}>
               
              <span><h1>Characters ({results.length})</h1> </span>
              
              </div>
              {results.map(result => {
                const {id, name , image,status ,species,location,episode} = result;
               
                return(
            <li key={id} className={styles.card}>
              <Link href="/characters/[id]" as={`/characters/${id}`}> 
              <a href="">
                <img src={image} alt={`$name`} className={styles.pict}/>
                <div className={styles.container__text}>
                <h1>{name}</h1>
                <br />
                <p><span className={styles.dot}></span>   {status} - {species}</p>
                <br />
                <p>Last known location:</p>
                <p>{location.name}</p>
                <br />
                <p>First seen in:</p>
                <p>{episode.name}</p>
                </div>
                </a> 
                </Link>
            </li>

                )
              })}
            </ul>
            
           

          
        </div> 
      </main>

    </div>
  )
}

const apiUrl = 'https://rickandmortyapi.com/api/character/'

export async function getStaticProps(context) {
  const res = await fetch(apiUrl);
  const data = await res.json();
  return {
    props: {
      data
    }, 
  }
}